
--CRIAR A TABELA DE USUÁRIO
CREATE TABLE [USUARIO](
	[COD_LEGADO] [bigint] NOT NULL PRIMARY KEY NONCLUSTERED, 
	[COD_USUARIO] [int]  NOT NULL,
	[NOME_USUARIO] [varchar](100) NOT NULL,
	[DT_NASCIMENTO] [date] NOT NULL,
	[COD_CPF] [varchar](13) NOT NULL,
	[SIGLA_FILIAL] [char](2) NULL,
	[NUM_NOTA] [int] NULL,
	[SIGL_GENERO] [char](1) NULL,
	[COD_RG] [int] NULL
);

--CRIAR UM ÍNDICE CLUSTER
CREATE CLUSTERED INDEX IDX_USUARIO
      ON USUARIO (COD_USUARIO);
  GO

--CRIAR ÍNDICE NÃO-CLUSTER
CREATE NONCLUSTERED INDEX IDX01_USUARIO
      ON USUARIO (DT_NASCIMENTO);
  GO

--CRIAR ÍNDICE ÚNICO
CREATE UNIQUE INDEX IDX02_USUARIO
      ON USUARIO (COD_CPF);
  GO

--CRIAR ÍNDICE FILTRADO
CREATE NONCLUSTERED INDEX IDX03_USUARIO
      ON USUARIO (SIGLA_FILIAL)
WHERE SIGLA_FILIAL = 'SP';
  GO

--CRIAR ÍNDICE COM COLUNAS INCLUÍDAS
CREATE NONCLUSTERED INDEX IDX04_USUARIO
      ON USUARIO (NUM_NOTA)
INCLUDE (NOME_USUARIO, SIGL_GENERO, COD_RG);
  GO
